"""add room_id to requests

Revision ID: a13360f392fe
Revises: abf2dde9f6a2
Create Date: 2025-11-06 23:40:18.407471+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13360f392fe'
down_revision: Union[str, Sequence[str], None] = 'abf2dde9f6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('room_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'requests', ['room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='unique')
    op.drop_column('requests', 'room_id')
    # ### end Alembic commands ###
